
-- CREATE DATABASE test

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons] (
	ID        INT IDENTITY (1, 1) PRIMARY KEY,
	LastName  VARCHAR(255) NOT NULL,
	FirstName VARCHAR(255),
	Age       INT
)

GO
